import LogService from '@taikai/scribal';

const blackListParams = [
  'reCaptchaSecret',
  'prismaSecret',
  'appSecret',
  'sslPrivateKeyPath',
  'sslCertPath',
  'sslPrivateKeyPassphrase',
  'corsAllowedOrigins',
  'googleProjectId',
  'googleCloudBucketId',
  'secretToken',
  'password',
  'dsn',
  'apiKey',
  'newsletterListID',
  'oauth2',
  'authPath',
  'clientId',
  'clientSecret',
  'eos',
  'contractAccount',
  'privateKey',
  'eosNodeURL',
  'keosdNodeURL',
  'userKey',
  'secret',
  'accountSID',
  'authToken',
  'verificationSID',
  'tokenID',
  'tokenSecret',
  'webhookSecret',
  'youtubeAPIKey',
  'vimeoClientId',
  'vimeoClientSecret',
  'vimeoAccessToken',
  'apolloAPIKey',
  'apolloActive',
  'mixPanelToken',
  'sgAPIKey',
  'databaseUrl',
  'redisHostname',
  'serverUrl',
  'githubUsername',
  'tokens',
  'token',
];

const log = new LogService(blackListParams, '*');

export default log;
