import { ChainIds, ChainSupported } from '../types';

export const chainsSupported: ChainSupported = {
  ethereum: {
    id: ChainIds.ETHEREUM,
    rpcUrl: `https://mainnet.infura.io/v3/${process.env.INFURA_PROJECT_KEY}`,
    wsUrl: `wss://mainnet.infura.io/ws/v3/${process.env.INFURA_PROJECT_KEY}`,
    blockExplorer: 'https://etherscan.io',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Ethereum Main Net',
    shortName: 'Ethereum',
    primaryColor: '#DDDDDD',
  },
  sepolia: {
    id: ChainIds.SEPOLIA,
    rpcUrl: `https://sepolia.infura.io/v3/${process.env.INFURA_PROJECT_KEY}`,
    wsUrl: `wss://sepolia.infura.io/ws/v3/${process.env.INFURA_PROJECT_KEY}`,
    blockExplorer: 'https://sepolia.etherscan.io/',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Sepolia Test Net',
    shortName: 'Sepolia',
    primaryColor: '#DDDDDD',
  },
  goerli: {
    id: ChainIds.GOERLI,
    rpcUrl: `https://goerli.infura.io/v3/${process.env.INFURA_PROJECT_KEY}`,
    wsUrl: `wss://goerli.infura.io/ws/v3/${process.env.INFURA_PROJECT_KEY}`,
    blockExplorer: 'https://goerli.etherscan.io/',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Goerli Test Net',
    shortName: 'Goerli',
    primaryColor: '#DDDDDD',
  },
  mumbai: {
    id: ChainIds.MUMBAI,
    rpcUrl: `https://polygon-mumbai.infura.io/v3/${process.env.INFURA_PROJECT_KEY}`,
    wsUrl: `wss://polygon-mumbai.infura.io/ws/v3/${process.env.INFURA_PROJECT_KEY}`,
    blockExplorer: 'https://etherscan.io',
    currency: 'MATIC',
    currencyDecimals: 18,
    name: 'Polygon Test Net',
    shortName: 'Polygon Test',
    primaryColor: '#DDDDDD',
  },
  polygon: {
    id: ChainIds.POLYGON,
    rpcUrl: `https://polygon-mainnet.infura.io/v3/${process.env.INFURA_PROJECT_KEY}`,
    wsUrl: `wss://polygon-mainnet.infura.io/ws/v3/${process.env.INFURA_PROJECT_KEY}`,
    blockExplorer: 'https://polygonscan.io',
    currency: 'MATIC',
    currencyDecimals: 18,
    name: 'Mumbai Main Net',
    shortName: 'Polygon Test',
    primaryColor: '#DDDDDD',
  },
  local: {
    id: ChainIds.LOCAL,
    rpcUrl: 'http://localhost:8545',
    wsUrl: 'ws://localhost:8545',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Ganache Local Network',
    shortName: 'Local',
    primaryColor: '#DDDDDD',
  },
};
