import { ChainIds, ChainSupported } from '../types';

export const chainsSupported: ChainSupported = {
  ethereum: {
    id: ChainIds.ETHEREUM,
    rpcUrl: process.env.WEB3_RPC_URL || 'https://eth.llamarpc.com',
    wsUrl: process.env.WEB3_WS_URL || 'wss://eth.drpc.org',
    blockExplorer: 'https://etherscan.io',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Ethereum Main Net',
    shortName: 'Ethereum',
    primaryColor: '#DDDDDD',
  },
  sepolia: {
    id: ChainIds.SEPOLIA,
    rpcUrl: process.env.WEB3_RPC_URL || 'https://rpc2.sepolia.org',
    wsUrl: process.env.WEB3_WS_URL || 'wss://sepolia.drpc.org',
    blockExplorer: 'https://sepolia.etherscan.io/',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Sepolia Test Net',
    shortName: 'Sepolia',
    primaryColor: '#DDDDDD',
  },
  goerli: {
    id: ChainIds.GOERLI,
    rpcUrl: process.env.WEB3_RPC_URL || 'https://eth-goerli.public.blastapi.io',
    wsUrl: process.env.WEB3_WS_URL || 'wss://goerli.gateway.tenderly.co',
    blockExplorer: 'https://goerli.etherscan.io/',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Goerli Test Net',
    shortName: 'Goerli',
    primaryColor: '#DDDDDD',
  },
  mumbai: {
    id: ChainIds.MUMBAI,
    rpcUrl: process.env.WEB3_RPC_URL || 'https://polygon-mumbai.gateway.tenderly.co',
    wsUrl: process.env.WEB3_WS_URL || 'wss://polygon-mumbai.gateway.tenderly.co',
    blockExplorer: 'https://etherscan.io',
    currency: 'MATIC',
    currencyDecimals: 18,
    name: 'Polygon Test Net',
    shortName: 'Polygon Test',
    primaryColor: '#DDDDDD',
  },
  polygon: {
    id: ChainIds.POLYGON,
    rpcUrl: process.env.WEB3_RPC_URL || 'https://polygon.llamarpc.com',
    wsUrl: process.env.WEB3_WS_URL || 'wss://polygon.drpc.org',
    blockExplorer: 'https://polygonscan.io',
    currency: 'MATIC',
    currencyDecimals: 18,
    name: 'Mumbai Main Net',
    shortName: 'Polygon Test',
    primaryColor: '#DDDDDD',
  },
  // Arbitrum One Main Net
  arbitrum: {
    id: ChainIds.ARBITRUM_MAIN_NET,
    name: 'Arbitrum One Main Net',
    shortName: 'arbitrum',
    rpcUrl: process.env.WEB3_RPC_URL || 'https://arbitrum.llamarpc.com',
    wsUrl: process.env.WEB3_WS_URL || 'wss://arbitrum-one.publicnode.com',
    currency: 'ETH',
    currencyDecimals: 18,
    blockExplorer: 'https://arbiscan.io',
    primaryColor: '#DDDDDD',
  },
  // Optimism Main Net
  optimism: {
    id: ChainIds.OPTIMISM_MAIN_NET,
    name: 'Optimism Main Net',
    shortName: 'optimism',
    rpcUrl: process.env.WEB3_RPC_URL || 'https://optimism.llamarpc.com',
    wsUrl: process.env.WEB3_WS_URL || 'wss://optimism.drpc.org',
    currency: 'ETH',
    currencyDecimals: 18,
    blockExplorer: 'https://optimistic.etherscan.io/',
    primaryColor: '#DDDDDD',
  },
  // Base Main Net
  base: {
    id: ChainIds.BASE_MAIN_NET,
    name: 'Base Main Net',
    shortName: 'base',
    rpcUrl: process.env.WEB3_RPC_URL || 'https://base.llamarpc.com',
    wsUrl: process.env.WEB3_WS_URL || 'wss://base-rpc.publicnode.com',
    currency: 'ETH',
    currencyDecimals: 18,
    blockExplorer: 'https://basescan.io/',
    primaryColor: '#DDDDDD',
  },
  local: {
    id: ChainIds.LOCAL,
    rpcUrl:  process.env.WEB3_RPC_URL || 'http://127.0.0.1:8545',
    wsUrl: process.env.WEB3_WS_URL || 'ws://127.0.0.1:8545',
    currency: 'ETH',
    currencyDecimals: 18,
    name: 'Ganache Network',
    shortName: 'Local',
    primaryColor: '#DDDDDD',
  },
};
